spring.application.name=core

# Active profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:test}

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.gach.core.controller
springdoc.paths-to-match=/**


# Logging
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.root=INFO